name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn lint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['10.17.0', '12.0.0']
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - run: yarn --frozen-lockfile --ignore-engines
      - run: yarn build
      - run: yarn test
